export enum Categorie {
  PUP_H = "PUP_H",
  PUP_D = "PUP_D",
  MIN_H = "MIN_H",
  MIN_D = "MIN_D",
  KAD_H = "KAD_H",
  KAD_D = "KAD_D",
  ASP_H = "ASP_H",
  ASP_D = "ASP_D",
  JUN_H = "JUN_H",
  JUN_D = "JUN_D",
  SEN_H = "SEN_H",
  SEN_D = "SEN_D",
  VET1_H = "VET1_H",
  VET1_D = "VET1_D",
  VET2_H = "VET2_H",
  VET2_D = "VET2_D",
  VET3_H = "VET3_H",
  VET3_D = "VET3_D",
  MIX="MIX",
  MIX_J="MIX_J",
  ESTAFETTE="ESTAFETTE",
  HANDICAP_1="HANDICAP_1",
  HANDICAP_2="HANDICAP_2",
  HANDICAP_3="HANDICAP_3",
}
